const ActionConstants = {
   FETCH_PRODUCTS: "FETCH_PRODUCTS",
   FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
   FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR",
   INCREMENT_ITEM: "INCREMENT_ITEM",
   DECREMENT_ITEM: "DECREMENT_ITEM",
   CLEAR_ITEM: "CLEAR_ITEM",
   EMPTY_QUANTITY_ITEM: "EMPTY_QUANTITY_ITEM",
   CHECK_CONFIRM_ORDER: "CHECK_CONFIRM_ORDER",
   CONFIRM_ORDER_SUCCESS: "CONFIRM_ORDER_SUCCESS",
};

export { ActionConstants };